before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
    binary: "{{ .ProjectName }}"
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Branch={{.Branch}} -X main.Commit={{.ShortCommit}}
    main: ./cmd/sf

archives:
  - format: zip

checksum:
  algorithm: sha256
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
